<?php
    //connect
    $config_severname="localhost";
    $config_name="root";
    $config_password="";
    $config_database="e-learn-app";
    $conn=new mysqli($config_severname,$config_name,$config_password,$config_database) or die('connection failed');
    
    //Bảng User
    $myquery="CREATE TABLE IF NOT EXISTS user (
        user_id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(200) NOT NULL,
        email VARCHAR(200) NOT NULL UNIQUE,
        phoneNumber VARCHAR(10),
        password VARCHAR(255) NOT NULL,
        dateSignin DATETIME DEFAULT CURRENT_TIMESTAMP,
        role ENUM('admin','user') DEFAULT 'user',
        time_login DATETIME,
        time_logout DATETIME
    )";
    $result=$conn->query($myquery); // Thực thi câu lệnh tạo bảng

    //Bảng vocabulary_Set
    $myquery="CREATE TABLE IF NOT EXISTS vocabulary_set (
        vocabularySet_id INT AUTO_INCREMENT PRIMARY KEY,
        user_id INT,
        vocabulary_name VARCHAR(200) NOT NULL UNIQUE,
        description TEXT,
        vocabulary_type ENUM ('personal', 'default') NOT NULL,
        FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
    )";
    $result=$conn->query($myquery);

    //Bảng Flashcard
    $myquery="CREATE TABLE IF NOT EXISTS flashcard (
        flashcard_id INT AUTO_INCREMENT PRIMARY KEY,
        vocabularySet_id INT,
        vocab VARCHAR(100) NOT NULL,
        image_path VARCHAR(255),
        ipa VARCHAR(100),
        meaning TEXT NOT NULL,
        flashcard_type VARCHAR(50),
        example TEXT,
        FOREIGN KEY (vocabularySet_id) REFERENCES vocabulary_set(vocabularySet_id) ON DELETE CASCADE
    )";
    $result=$conn->query($myquery);

    //Bảng game_history
    $myquery="CREATE TABLE IF NOT EXISTS history (
    history_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    activity_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    duration TIME,
    FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
    )";
    $result=$conn->query($myquery);

    //Bảng Thông báo
    $myquery="CREATE TABLE IF NOT EXISTS reminder (
        reminder_id INT PRIMARY KEY AUTO_INCREMENT,
        user_id INT NOT NULL,
        reminder_date DATE NOT NULL,
        status ENUM ('Complete','Pending') DEFAULT 'Pending',
        FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
        )";
    $result=$conn->query($myquery);

    //bảng tin nhắn
    $myquery = "CREATE TABLE IF NOT EXISTS default_messages (
        message_id INT AUTO_INCREMENT PRIMARY KEY,
        message_type ENUM('daily', '48_hours') NOT NULL,
        message_text TEXT NOT NULL
    )";
    $result=$conn->query($myquery); // Thực thi câu lệnh tạo bảng

    //insert
    $insert_user_query = "
    INSERT INTO user (username, email, phoneNumber, password, role)
    VALUES 
    ('admin', 'admin@gmail.com', '0123456789', '" . password_hash("123", PASSWORD_DEFAULT) . "', 'admin'),
    ('user1', 'user@gmail.com', '0987654321', '" . password_hash("123", PASSWORD_DEFAULT) . "', 'user')
    ";
    //$conn->query($insert_user_query);


    // Thêm dữ liệu mẫu vào bảng vocabulary_set
    $insert_vocabulary_set_query = "
        INSERT INTO vocabulary_set (user_id, vocabulary_name, description, vocabulary_type)
        VALUES 
        (1, 'Common Words', 'A set of common English words.', 'default'),
        (2, 'Personal List', 'User-defined vocabulary list.', 'personal')
    ";
    //$conn->query($insert_vocabulary_set_query);


    // Thêm dữ liệu mẫu vào bảng flashcard
    $insert_flashcard_query = "
        INSERT INTO flashcard (vocabularySet_id, vocab, image_path, ipa, meaning, flashcard_type, example)
        VALUES 
        (17, 'Airline schedule', 'airline_schedule.png', '/ˈeəlaɪn ˈʃedjuːl/', 'Lịch bay', 'noun', 'The airline schedule shows all flights for the day.'),
        (17, 'Baggage allowance', 'baggage_allowance.png', '/ˈbæɡɪdʒ əˈlaʊəns/', 'Lượng hành lý cho phép', 'noun', 'The baggage allowance for this flight is 20 kilograms.'),
        (17, 'Boarding pass', 'boarding_pass.png', '/ˈbɔːdɪŋ kɑːd/', 'Thẻ lên máy bay', 'noun', 'Please show your boarding pass at the gate.'),
        (17, 'Check-in', 'check_in.png', '/tʃek – ɪn/', 'Thủ tục vào cửa', 'noun', 'You should arrive two hours early for check-in.'),
        (17, 'Deposit', 'deposit.png', '/dɪˈpɒzɪt/', 'Đặt cọc', 'noun', 'You need to pay a deposit to secure your booking.'),
        (17, 'Domestic travel', 'domestic_travel.png', '/dəˈmestɪk ˈtrævl/', 'Du lịch nội địa', 'noun', 'Domestic travel is increasing in popularity.'),
        (17, 'Destination', 'destination.png', '/ˌdestɪˈneɪʃn/', 'Điểm đến', 'noun', 'Paris is a popular tourist destination.'),
        (17, 'High season', 'high_season.png', '/haɪ ˈsiːzn/', 'Mùa cao điểm', 'noun', 'Hotel prices are higher during high season.'),
        (17, 'Low season', 'low_season.png', '/ləʊˈsiːzn/', 'Mùa ít khách', 'noun', 'You can find cheaper tickets during low season.'),
        (17, 'Loyalty programme', 'loyalty_programme.png', '/ˈlɔɪəltiˈprəʊɡræm/', 'Chương trình cho khách hàng thường xuyên', 'noun', 'Frequent flyers benefit from the airline loyalty programme.'),
        (17, 'Inclusive tour', 'inclusive_tour.png', '/ɪnˈkluːsɪv tʊə(r)/', 'Tour trọn gói', 'noun', 'The inclusive tour covers accommodation, meals, and transportation.'),
        (17, 'One way trip', 'one_way_trip.png', '/wʌn weɪ trɪp/', 'Chuyến đi 1 chiều', 'noun', 'He booked a one way trip to New York.'),
        (17, 'Round trip', 'round_trip.png', '/ˌraʊnd ˈtrɪp/', 'Chuyến đi khứ hồi', 'noun', 'A round trip ticket is often cheaper than two one way tickets.'),
        (17, 'Itinerary', 'itinerary.png', '/aɪˈtɪnərəri/', 'Lịch trình', 'noun', 'The travel agency sent us a detailed itinerary for the tour.'),
        (18, 'Ruler', 'ruler.png', '/ˈruːlə/', 'Thước kẻ', 'noun', 'She used a ruler to draw straight lines.'),
        (18, 'Blackboard', 'blackboard.png', '/ˈblækbɔːd/', 'Bảng đen', 'noun', 'The teacher wrote the lesson on the blackboard.'),
        (18, 'Chalk', 'chalk.png', '/ʧɔːk/', 'Phấn viết bảng', 'noun', 'He drew a diagram on the blackboard with chalk.'),
        (18, 'Chair', 'chair.png', '/ʧeə/', 'Ghế', 'noun', 'Each student has a chair in the classroom.'),
        (18, 'Desk', 'desk.png', '/dɛsk/', 'Bàn học', 'noun', 'The desk was covered with books and papers.'),
        (18, 'Clock', 'clock.png', '/klɒk/', 'Đồng hồ', 'noun', 'There is a clock on the wall to check the time.'),
        (18, 'Pen', 'pen.png', '/pɛn/', 'Cái bút', 'noun', 'He signed the document with a blue pen.'),
        (18, 'Pencil', 'pencil.png', '/ˈpɛnsl/', 'Bút chì', 'noun', 'She used a pencil to sketch the picture.'),
        (18, 'Notebook', 'notebook.png', '/ˈnəʊtbʊk/', 'Quyển vở', 'noun', 'I wrote the lecture notes in my notebook.'),
        (18, 'Backpack', 'backpack.png', '/ˈbækˌpæk/', 'Cặp sách', 'noun', 'He packed his books into his backpack.'),
        (18, 'Scissors', 'scissors.png', '/ˈsɪzəz/', 'Kéo', 'noun', 'Use the scissors to cut the paper neatly.'),
        (18, 'Compass', 'compass.png', '/ˈkʌmpəs/', 'Com-pa', 'noun', 'The geometry set includes a compass for drawing circles.'),
        (18, 'Classmate', 'classmate.png', '/ˈklɑːsmeɪt/', 'Bạn cùng lớp', 'noun', 'My classmate helped me with the homework.'),
        (18, 'Break time', 'break_time.png', '/breɪk taɪm/', 'Giờ ra chơi', 'noun', 'We played football during break time.'),
        (18, 'International school', 'international_school.png', '/ˌɪntə(ː)ˈnæʃənl skuːl/', 'Trường quốc tế', 'noun', 'Her children attend an international school.'),
        (18, 'Boarding school', 'boarding_school.png', '/ˈbɔːdɪŋ skuːl/', 'Trường nội trú', 'noun', 'He spent his teenage years in a boarding school.'),
        (18, 'Elementary school', 'elementary_school.png', '/ˌɛlɪˈmɛntəri skuːl/', 'Trường tiểu học', 'noun', 'Elementary school is where children learn basic skills.'),
        (18, 'Secondary school', 'secondary_school.png', '/ˈsɛkəndəri skuːl/', 'Trường cấp hai', 'noun', 'He graduated from secondary school last year.'),
        (18, 'High school', 'high_school.png', '/ˈhaɪ ˌskuːl/', 'Trường cấp ba', 'noun', 'She is a senior in high school.'),
        (18, 'Kindergarten', 'kindergarten.png', '/ˈkɪndəˌgɑːtn/', 'Trường mầm non', 'noun', 'The child is in kindergarten and learning to write.'),
        (18, 'Computer room', 'computer_room.png', '/kəmˈpjuːtə ruːm/', 'Phòng máy tính', 'noun', 'The computer room is equipped with new devices.'),
        (18, 'Library', 'library.png', '/ˈlaɪbrəri/', 'Thư viện', 'noun', 'She borrowed books from the school library.'),
        (18, 'School garden', 'school_garden.png', '/skuːl ˈgɑːdn/', 'Sân vườn trường', 'noun', 'Students take care of plants in the school garden.'),
        (18, 'Club', 'club.png', '/klʌb/', 'Câu lạc bộ', 'noun', 'She joined the drama club at school.'),
        (18, 'Subject', 'subject.png', '/ˈsʌbʤɪkt/', 'Môn học', 'noun', 'Mathematics is his favorite subject.'),
        (18, 'English', 'english.png', '/ˈɪŋglɪʃ/', 'Tiếng Anh', 'noun', 'We have an English class every morning.'),
        (18, 'Mathematics', 'mathematics.png', '/ˌmæθɪˈmætɪks/', 'Môn toán', 'noun', 'She excels in mathematics.'),
        (18, 'Science', 'science.png', '/ˈsaɪəns/', 'Môn khoa học', 'noun', 'Science experiments are fun to do.'),
        (18, 'History', 'history.png', '/ˈhɪstəri/', 'Môn lịch sử', 'noun', 'He is studying the history of ancient civilizations.'),
        (18, 'Geography', 'geography.png', '/ʤɪˈɒgrəfi/', 'Môn địa lý', 'noun', 'We learned about different continents in geography.'),
        (18, 'Social studies', 'social_studies.png', '/ˈsəʊʃəl ˈstʌdiz/', 'Môn xã hội học', 'noun', 'Social studies covers culture and society.'),
        (18, 'Physics', 'physics.png', '/ˈfɪzɪks/', 'Môn vật lý', 'noun', 'The laws of motion are studied in physics.'),
        (18, 'Board', 'board.png', '/bɔːd/', 'Bảng viết', 'noun', 'The teacher wrote some notes on the board.'),
        (18, 'Conveying tube', 'conveying_tube.png', '/kənˈveɪ tuːb/', 'Ống nghiệm nuôi cấy vi sinh vật', 'noun', 'The conveying tube is used in biology experiments.'),
        (18, 'Duster', 'duster.png', '/ˈdʌstə/', 'Khăn lau bảng', 'noun', 'She cleaned the board with a duster.'),
        (18, 'Funnel', 'funnel.png', '/ˈfʌnl/', 'Cái phễu', 'noun', 'The funnel is used for pouring liquids.'),
        (18, 'Hole punch', 'hole_punch.png', '/ˈhoʊl ˌpʌntʃ/', 'Dụng cụ đục lỗ', 'noun', 'He used a hole punch to organize his papers.'),
        (18, 'Jigsaws', 'jigsaws.png', '/ˈdʒɪɡ.sɑː/', 'Miếng ghép hình', 'noun', 'The children enjoy solving jigsaws together.'),
        (18, 'Magnifying glass', 'magnifying_glass.png', '/ˈmæɡ.nɪ.faɪ.ɪŋ ˌɡlɑːs/', 'Kính lúp', 'noun', 'She examined the insect using a magnifying glass.'),
        (18, 'Paint', 'paint.png', '/peɪnt/', 'Sơn màu', 'noun', 'They used paint to create a beautiful artwork.'),
        (18, 'Palette', 'palette.png', '/ˈpælət/', 'Bảng màu', 'noun', 'The artist mixed colors on the palette.'),
        (18, 'Pipe cleaner', 'pipe_cleaner.png', '/ˌpaɪp ˈkliː.nɚ/', 'Thanh uốn lông', 'noun', 'Pipe cleaners are useful for craft projects.'),
        (18, 'Set square', 'set_square.png', '/ˈset ˌskweər/', 'Ê-ke', 'noun', 'The student used a set square to draw a perfect angle.'),
        (18, 'Table', 'table.png', '/ˈteibl/', 'Cái bàn', 'noun', 'The books are placed on the table.'),
        (18, 'Tape measure', 'tape_measure.png', '/ˈteɪp ˌmeʒ.ər/', 'Thước cuộn', 'noun', 'The tape measure is used to measure fabric.'),
        (18, 'Test tube', 'test_tube.png', '/ˈtest ˌtjuːb/', 'Ống thí nghiệm', 'noun', 'Chemicals were mixed in the test tube.'),
        (18, 'Thumbtack', 'thumbtack.png', '/ˈθʌmtæk/', 'Đinh ghim', 'noun', 'She pinned the note to the board with a thumbtack.'),
        (18, 'Fountain pen', 'fountain_pen.png', '/’faʊntinpen/', 'Bút máy', 'noun', 'He signed the certificate with a fountain pen.'),
        (18, 'Clipboard', 'clipboard.png', '/klɪp,boʊrd/', 'Bảng kẹp', 'noun', 'The coach carried a clipboard during the game.'),
        (19, 'Dry', 'dry.png', '/drai/', 'Hanh khô', 'adj', 'The weather was dry and perfect for hiking.'),
        (19, 'Foggy', 'foggy.png', '/’fɒgi/', 'Sương mù', 'adj', 'It was a foggy morning in the mountains.'),
        (19, 'Humid', 'humid.png', '/’hju:mid/', 'Ẩm', 'adj', 'The humid air made it difficult to stay cool.'),
        (19, 'Overcast', 'overcast.png', '/,əʊvə’kɑ:st/', 'Âm u', 'adj', 'The sky was overcast, but it didn’t rain.'),
        (19, 'Sunny', 'sunny.png', '/’sʌni/', 'Nắng', 'adj', 'It was a sunny day at the beach.'),
        (19, 'Cold', 'cold.png', '/koʊld/', 'Lạnh', 'adj', 'The weather turned cold overnight.'),
        (19, 'Freezing', 'freezing.png', '/’fri:ziɳ/', 'Lạnh cóng', 'adj', 'It was freezing outside, so we stayed indoors.'),
        (19, 'Warm', 'warm.png', '/wɔ:m/', 'Ấm áp', 'adj', 'The warm breeze made the evening pleasant.'),
        (19, 'Drizzle', 'drizzle.png', '/’drizl/', 'Cơn mưa phùn', 'noun', 'There was a light drizzle in the morning.'),
        (19, 'Flood', 'flood.png', '/flʌd/', 'Lũ lụt', 'noun', 'The flood caused severe damage to the town.'),
        (19, 'Hail', 'hail.png', '/heil/', 'Mưa đá', 'noun', 'The hail damaged several cars during the storm.'),
        (19, 'Gale', 'gale.png', '/geil/', 'Gió giật', 'noun', 'The gale knocked down several trees.'),
        (19, 'Rain', 'rain.png', '/rein/', 'Mưa', 'noun', 'The rain continued for hours, drenching everything.'),
        (20, 'Environment', 'environment.png', '/ɪnˈvaɪ.rən.mənt/', 'Môi trường', 'noun', 'We must take care of our environment.'),
        (20, 'Acid rain', 'acid_rain.png', '/æsɪd reɪn/', 'Mưa axit', 'noun', 'Acid rain is harmful to both animals and plants.'),
        (20, 'Air', 'air.png', '/eər/', 'Không khí', 'noun', 'The air feels fresh in the morning.'),
        (20, 'Air pollution', 'air_pollution.png', '/eər pəˈluː.ʃən/', 'Ô nhiễm không khí', 'noun', 'Air pollution is a serious issue in big cities.'),
        (20, 'Atmosphere', 'atmosphere.png', '/ˈæt.mə.sfɪər/', 'Khí quyển', 'noun', 'The atmosphere protects Earth from harmful radiation.'),
        (20, 'Biodiversity', 'biodiversity.png', '/ˌbaɪoʊdəˈvərsət̮i/', 'Đa dạng sinh học', 'noun', 'The Amazon rainforest is rich in biodiversity.'),
        (20, 'Biosphere reserve', 'biosphere_reserve.png', '/ˈbaɪoʊsfɪr rɪˈzɜːrv/', 'Khu dự trữ sinh quyển', 'noun', 'Many species are protected in the biosphere reserve.'),
        (20, 'Climate', 'climate.png', '/ˈklaɪ.mət/', 'Khí hậu', 'noun', 'The climate in this region is very mild.'),
        (20, 'Climate change', 'climate_change.png', '/ˈklaɪ.mət tʃeɪndʒ/', 'Biến đổi khí hậu', 'noun', 'Climate change is affecting weather patterns worldwide.'),
        (20, 'Deforestation', 'deforestation.png', '/ˌdiːˌfɑːrɪˈsteɪʃn/', 'Sự phá rừng', 'noun', 'Deforestation threatens many animal habitats.'),
        (20, 'Destruction', 'destruction.png', '/dɪsˈtrʌkʃən/', 'Sự phá hủy', 'noun', 'The destruction of forests has many environmental consequences.'),
        (20, 'Disposal', 'disposal.png', '/dɪsˈpəʊzəl/', 'Sự vứt bỏ', 'noun', 'Proper disposal of waste is essential to keep the environment clean.'),
        (20, 'Draught', 'draught.png', '/drɑːft/', 'Hạn hán', 'noun', 'The draught caused a shortage of water in the area.'),
        (20, 'Dust', 'dust.png', '/dʌst/', 'Bụi', 'noun', 'The table was covered in a layer of dust.'),
        (20, 'Ecosystem', 'ecosystem.png', '/ˈiː.kəʊˌsɪs.təm/', 'Hệ sinh thái', 'noun', 'Each part of the ecosystem is interconnected.'),
        (20, 'Forest fire', 'forest_fire.png', '/ˈfɒr.ɪst ˌfaɪər/', 'Cháy rừng', 'noun', 'Forest fires have destroyed thousands of acres of trees.'),
        (20, 'Greenhouse effect', 'greenhouse_effect.png', '/ˈɡriːnhaʊs ɪˈfekt/', 'Hiệu ứng nhà kính', 'noun', 'The greenhouse effect is caused by excessive carbon emissions.'),
        (20, 'Groundwater', 'groundwater.png', '/ˈɡraʊndwɔːtər/', 'Nước ngầm', 'noun', 'Groundwater levels are dropping due to overuse.'),
        (21, 'Dog', 'dog.png', '/dɒg/', 'Con chó', 'noun', 'The dog is barking loudly in the garden.'),
        (21, 'Cat', 'cat.png', '/kæt/', 'Con mèo', 'noun', 'The cat is sleeping under the table.'),
        (21, 'Goldfish', 'goldfish.png', '/ˈgəʊldfɪʃ/', 'Cá vàng', 'noun', 'I have a goldfish in a bowl at home.'),
        (21, 'Hamster', 'hamster.png', '/ˈhæmstə/', 'Chuột Hamster', 'noun', 'My sister keeps a hamster as a pet.'),
        (21, 'Kitten', 'kitten.png', '/ˈkɪtn/', 'Mèo con', 'noun', 'The kitten is so cute and playful.'),
        (21, 'Mouse', 'mouse.png', '/maʊs/', 'Chuột', 'noun', 'There is a small mouse hiding in the cupboard.'),
        (21, 'Parrot', 'parrot.png', '/ˈpærət/', 'Con vẹt', 'noun', 'The parrot can mimic human speech.'),
        (21, 'Puppy', 'puppy.png', '/ˈpʌpi/', 'Chó con, cún con', 'noun', 'She adopted a playful puppy from the shelter.'),
        (21, 'Rabbit', 'rabbit.png', '/ˈræbɪt/', 'Con thỏ', 'noun', 'The rabbit hopped across the lawn.'),
        (21, 'Squirrel', 'squirrel.png', '/ˈskwɪrəl/', 'Con sóc', 'noun', 'A squirrel climbed up the tree quickly.'),
        (21, 'Tropical fish', 'tropical_fish.png', '/ˈtrɒpɪkəl fɪʃ/', 'Cá nhiệt đới', 'noun', 'My aquarium is full of colorful tropical fish.'),
        (21, 'Turtle', 'turtle.png', '/ˈtɜːtl/', 'Rùa', 'noun', 'The turtle is slowly moving towards the water.'),
        (21, 'Cow', 'cow.png', '/kaʊ/', 'Con bò', 'noun', 'The cow provides milk for the farm.'),
        (21, 'Bee', 'bee.png', '/biː/', 'Con ong', 'noun', 'Bees are important for pollinating plants.'),
        (21, 'Chicken', 'chicken.png', '/ˈʧɪkɪn/', 'Con gà', 'noun', 'The chicken laid three eggs this morning.'),
        (21, 'Crab', 'crab.png', '/kræb/', 'Cua', 'noun', 'We saw a crab on the beach during our walk.'),
        (21, 'Deer', 'deer.png', '/dɪə/', 'Con nai', 'noun', 'A deer appeared in the forest clearing.'),
        (21, 'Dove', 'dove.png', '/dʌv/', 'Chim bồ câu', 'noun', 'The dove is a symbol of peace.'),
        (21, 'Ducks', 'ducks.png', '/dʌks/', 'Con vịt', 'noun', 'The ducks are swimming in the pond.'),
        (21, 'Fish', 'fish.png', '/fɪʃ/', 'Cá', 'noun', 'I caught a big fish while fishing today.'),
        (21, 'Goat', 'goat.png', '/gəʊt/', 'Con dê', 'noun', 'The goat is grazing on the hill.'),
        (21, 'Horse', 'horse.png', '/hɔːs/', 'Con ngựa', 'noun', 'He enjoys riding his horse every weekend.'),
        (21, 'Pig', 'pig.png', '/pɪg/', 'Con lợn', 'noun', 'The pig rolled in the mud to cool off.'),
        (21, 'Sheep', 'sheep.png', '/ʃiːp/', 'Cừu', 'noun', 'The farmer has a large flock of sheep.'),
        (21, 'Shrimp', 'shrimp.png', '/ʃrɪmp/', 'Con tôm', 'noun', 'We had grilled shrimp for dinner.'),
        (21, 'Turkey', 'turkey.png', '/ˈtɜːki/', 'Gà tây', 'noun', 'Turkey is a traditional dish for Thanksgiving.'),
        (22, 'Rice', 'rice.png', '/rīs/', 'Cơm trắng', 'noun', 'I always eat rice with vegetables for lunch.'),
        (22, 'Fried rice', 'fried_rice.png', '/fraɪd raɪs/', 'Cơm chiên', 'noun', 'Fried rice is a popular dish in many Asian countries.'),
        (22, 'Noodles', 'noodles.png', '/ˈnuːdl/', 'Bún, phở, mì', 'noun', 'I had a bowl of noodles for breakfast this morning.'),
        (22, 'Porridge', 'porridge.png', '/ˈpɒrɪdʒ/', 'Cháo', 'noun', 'My grandmother makes delicious chicken porridge.'),
        (22, 'Cereals', 'cereals.png', '/ˈsɪəriəl/', 'Ngũ cốc', 'noun', 'I usually have cereals with milk for breakfast.'),
        (22, 'Dumplings', 'dumplings.png', '/ˈdʌmplɪŋ/', 'Bánh bao hấp', 'noun', 'We served steamed dumplings at the family dinner.'),
        (22, 'Grilled lamb chops', 'grilled_lamb_chops.png', '/ɡrɪld læm tʃɒp/', 'Sườn cừu nướng', 'noun', 'The grilled lamb chops were seasoned perfectly.'),
        (22, 'Curry', 'curry.png', '/ˈkʌr.i/', 'Cà ri', 'noun', 'The chicken curry is spicy and flavorful.'),
        (22, 'Hotpot', 'hotpot.png', '/ˈhɒt.pɒt/', 'Lẩu', 'noun', 'We enjoyed a seafood hotpot during the cold evening.'),
        (22, 'Spaghetti', 'spaghetti.png', '/spəˈɡet.i/', 'Mỳ Ý', 'noun', 'Spaghetti with tomato sauce is my favorite meal.'),
        (22, 'Pasta', 'pasta.png', '/ˈpɑːstə/', 'Mì ống, mì sợi', 'noun', 'Italian pasta dishes are very popular worldwide.'),
        (22, 'Smoked salmon', 'smoked_salmon.png', '/sməʊkt ˈsæm.ən/', 'Cá hồi hun khói', 'noun', 'She served smoked salmon on toast as an appetizer.'),
        (22, 'Roasted duck', 'roasted_duck.png', '/roʊstəd dʌk/', 'Vịt nướng', 'noun', 'The roasted duck was tender and delicious.'),
        (22, 'Freshwater fish', 'freshwater_fish.png', '/ˈfrɛˌʃwɔtər fɪʃ/', 'Cá nước ngọt', 'noun', 'Freshwater fish is often used in traditional Vietnamese dishes.'),
        (22, 'Seafood', 'seafood.png', '/ˈsiː.fuːd/', 'Hải sản', 'noun', 'Seafood platters are a must-try when visiting the coast.'),
        (22, 'Shrimps', 'shrimps.png', '/ʃrɪmps/', 'Tôm', 'noun', 'We ordered a plate of garlic butter shrimps.'),
        (22, 'Snails', 'snails.png', '/sneɪlz/', 'Ốc', 'noun', 'Snails cooked with lemongrass are a local delicacy.'),
        (22, 'Squid', 'squid.png', '/skwɪd/', 'Mực', 'noun', 'Grilled squid is a favorite street food in Vietnam.'),
        (22, 'Mackerel', 'mackerel.png', '/ˈmæk.rəl/', 'Cá thu', 'noun', 'Mackerel is often served with a tangy tomato sauce.'),
        (22, 'Sole', 'sole.png', '/səʊl/', 'Cá bơn', 'noun', 'The chef prepared the sole with a lemon butter sauce.'),
        (22, 'Tuna', 'tuna.png', '/tuː.nə/', 'Cá ngừ', 'noun', 'Tuna salad is a healthy and refreshing dish.'),
        (22, 'Octopus', 'octopus.png', '/ˈɒk.tə.pəs/', 'Bạch tuộc', 'noun', 'Grilled octopus is a popular Mediterranean delicacy.'),
        (22, 'Chicken breasts', 'chicken_breasts.png', '/ˈtʃɪkɪn brest/', 'Ức gà', 'noun', 'Chicken breasts are a great source of lean protein.'),
        (22, 'Chicken drumsticks', 'chicken_drumsticks.png', '/ˈtʃɪkɪn ˈdrʌmstɪk/', 'Đùi gà', 'noun', 'The chicken drumsticks were marinated in barbecue sauce.'),
        (22, 'Cold cuts', 'cold_cuts.png', '/ˈkəʊld kʌts/', 'Thịt nguội', 'noun', 'We prepared sandwiches with a variety of cold cuts.'),
        (22, 'Pork side', 'pork_side.png', '/pɔːk saɪd/', 'Thịt ba chỉ', 'noun', 'Pork side is ideal for making crispy pork belly dishes.'),
        (23, 'Beer', 'beer.png', '/bɪə/', 'Bia', 'noun', 'Would you like a bottle of beer with your meal?'),
        (23, 'Chocolate milk', 'chocolate_milk.png', '/ˈʧɒkəlɪt mɪlk/', 'Sô cô la sữa', 'noun', 'Children often enjoy a glass of chocolate milk.'),
        (23, 'Cocoa', 'cocoa.png', '/ˈkəʊkəʊ/', 'Ca cao', 'noun', 'A hot cup of cocoa is perfect on a cold day.'),
        (23, 'Coconut milk', 'coconut_milk.png', '/ˈkəʊkənʌt mɪlk/', 'Sữa dừa', 'noun', 'Coconut milk is often used in Thai curry dishes.'),
        (23, 'Coffee', 'coffee.png', '/ˈkɒfi/', 'Cà phê', 'noun', 'I start my day with a strong cup of coffee.'),
        (23, 'Fruit juice', 'fruit_juice.png', '/fruːt ʤuːs/', 'Nước hoa quả', 'noun', 'Fresh fruit juice is a healthy option for breakfast.'),
        (23, 'Green tea', 'green_tea.png', '/griːn tiː/', 'Trà xanh', 'noun', 'Green tea is known for its health benefits.'),
        (23, 'Hot chocolate', 'hot_chocolate.png', '/hɒt ˈʧɒkəlɪt/', 'Sô cô la nóng', 'noun', 'Hot chocolate with whipped cream is a treat.'),
        (23, 'Iced tea', 'iced_tea.png', '/aɪst tiː/', 'Trà đá', 'noun', 'Iced tea is refreshing on a hot day.'),
        (23, 'Juice', 'juice.png', '/ʤuːs/', 'Nước ép', 'noun', 'Orange juice is rich in vitamin C.'),
        (23, 'Lemonade', 'lemonade.png', '/ˌlɛməˈneɪd/', 'Nước chanh', 'noun', 'Homemade lemonade is the best on a sunny afternoon.'),
        (23, 'Milk', 'milk.png', '/mɪlk/', 'Sữa', 'noun', 'Milk is essential for growing children.'),
        (23, 'Milkshake', 'milkshake.png', '/ˈmɪlkʃeɪk/', 'Sữa lắc', 'noun', 'We ordered chocolate milkshakes at the café.'),
        (23, 'Orange juice', 'orange_juice.png', '/ˈɒrɪnʤ ʤuːs/', 'Nước cam', 'noun', 'A glass of orange juice pairs well with breakfast.'),
        (23, 'Smoothie', 'smoothie.png', '/ˈsmuːði/', 'Sinh tố', 'noun', 'A berry smoothie is a quick and healthy snack.'),
        (23, 'Soda', 'soda.png', '/ˈsəʊdə/', 'Nước ngọt', 'noun', 'Many people enjoy soda with their meals.'),
        (23, 'Tea', 'tea.png', '/tiː/', 'Trà', 'noun', 'A warm cup of tea can be very relaxing.'),
        (23, 'Tea bag', 'tea_bag.png', '/tiː bæg/', 'Trà túi lọc', 'noun', 'She brewed her tea using a tea bag.'),
        (23, 'Tomato juice', 'tomato_juice.png', '/təˈmɑːtəʊ ʤuːs/', 'Nước ép cà chua', 'noun', 'Tomato juice is served on most flights.'),
        (23, 'Water', 'water.png', '/ˈwɔːtə/', 'Nước uống', 'noun', 'Staying hydrated with water is important.'),
        (23, 'Wine', 'wine.png', '/waɪn/', 'Rượu', 'noun', 'They ordered a bottle of red wine for dinner.'),
        (24, 'Black', 'black.png', '/blæk/', 'Màu đen', 'adj', 'She wore a beautiful black dress to the party.'),
        (24, 'White', 'white.png', '/waɪt/', 'Màu trắng', 'adj', 'The walls of the room were painted white.'),
        (24, 'Red', 'red.png', '/red/', 'Màu đỏ', 'adj', 'He gave her a red rose as a gift.'),
        (24, 'Yellow', 'yellow.png', '/ˈjel.əʊ/', 'Màu vàng', 'adj', 'The bright yellow sunflowers are stunning.'),
        (24, 'Orange', 'orange.png', '/ˈɒr.ɪndʒ/', 'Màu cam', 'adj', 'She bought an orange scarf to match her outfit.'),
        (24, 'Purple', 'purple.png', '/ˈpɜː(ɹ).pəl/', 'Màu tím', 'adj', 'The sky turned purple during the sunset.'),
        (24, 'Blue', 'blue.png', '/bluː/', 'Màu xanh', 'adj', 'The ocean looks so blue and calm today.'),
        (24, 'Green', 'green.png', '/griːn/', 'Màu xanh lá', 'adj', 'The garden is full of green plants.'),
        (24, 'Brown', 'brown.png', '/braʊn/', 'Màu nâu', 'adj', 'She painted the wooden fence brown.'),
        (24, 'Gray/Grey', 'gray_grey.png', '/greɪ/', 'Màu xám', 'adj', 'The sky looks gray before the rain starts.'),
        (24, 'Pink', 'pink.png', '/pɪŋk/', 'Màu hồng', 'adj', 'She decorated her room with pink curtains.'),
        (24, 'Turquoise', 'turquoise.png', '/ˈtɜː.kwɔɪz/', 'Màu lam', 'adj', 'The turquoise waters of the lagoon are breathtaking.'),
        (24, 'Dark Green', 'dark_green.png', '/dɑːk griːn/', 'Xanh lá cây đậm', 'adj', 'The forest is full of dark green trees.'),
        (24, 'Light Blue', 'light_blue.png', '/laɪt bluː/', 'Xanh nhạt', 'adj', 'She loves the light blue shade of her new dress.'),
        (24, 'Navy', 'navy.png', '/ˈneɪ.vi/', 'Xanh da trời đậm', 'adj', 'He bought a navy jacket for the winter season.'),
        (25, 'Applaud', 'applaud.png', '/əˈplɔd/', 'Vỗ tay, tán thưởng', 'verb', 'The audience applauded after the performance.'),
        (25, 'Art', 'art.png', '/ɑrt/', 'Nghệ thuật', 'noun', 'She loves studying modern art in museums.'),
        (25, 'Artist', 'artist.png', '/ˈɑrtɪst/', 'Nghệ sĩ', 'noun', 'The artist painted a beautiful landscape.'),
        (25, 'Artwork', 'artwork.png', '/ˈɑrˌtwɜrk/', 'Tác phẩm nghệ thuật', 'noun', 'The gallery displayed various artworks from the 18th century.'),
        (25, 'Audience', 'audience.png', '/ˈɔdiəns/', 'Khán giả', 'noun', 'The audience cheered for the performers.'),
        (25, 'Author', 'author.png', '/ˈɔθər/', 'Tác giả', 'noun', 'She is the author of several bestselling novels.'),
        (25, 'Band', 'band.png', '/bænd/', 'Ban nhạc', 'noun', 'The band performed their new song at the concert.'),
        (25, 'Brush', 'brush.png', '/brʌʃ/', 'Cọ vẽ', 'noun', 'The artist used a fine brush to add details to the painting.'),
        (25, 'Camera', 'camera.png', '/ˈkæmrə/', 'Máy ảnh', 'noun', 'He took several photos with his camera during the trip.'),
        (25, 'Canvas', 'canvas.png', '/ˈkænvəs/', 'Tấm vải vẽ tranh sơn dầu', 'noun', 'The artist stretched the canvas before starting to paint.'),
        (25, 'Choir', 'choir.png', '/ˈkwaɪər/', 'Dàn hợp xướng', 'noun', 'The choir sang beautiful hymns during the service.'),
        (25, 'Clap', 'clap.png', '/klæp/', 'Vỗ tay', 'verb', 'The audience clapped loudly after the performance.'),
        (25, 'Collection', 'collection.png', '/kəˈlɛkʃən/', 'Bộ sưu tập', 'noun', 'His collection of ancient coins is impressive.'),
        (25, 'Composer', 'composer.png', '/kəmˈpoʊzər/', 'Nhà soạn nhạc', 'noun', 'Beethoven was a famous composer of classical music.'),
        (25, 'Concert', 'concert.png', '/kənˈsɜrt/', 'Buổi trình diễn âm nhạc', 'noun', 'They went to a rock concert last weekend.'),
        (25, 'Creative', 'creative.png', '/kriˈeɪtɪv/', 'Tính sáng tạo', 'adj', 'She is very creative and loves to paint.'),
        (25, 'Culture', 'culture.png', '/ˈkʌlʧər/', 'Văn hóa', 'noun', 'The museum showcases the culture of ancient civilizations.'),
        (25, 'Design', 'design.png', '/dɪˈzaɪn/', 'Thiết kế', 'verb', 'The designer will design the new logo for the company.'),
        (25, 'Drawing', 'drawing.png', '/ˈdrɔɪŋ/', 'Bức tranh vẽ', 'noun', 'Her drawing of the landscape was beautiful.'),
        (25, 'Exhibition', 'exhibition.png', '/ˌɛksəˈbɪʃən/', 'Triển lãm', 'noun', 'The art exhibition features works from famous painters.'),
        (25, 'Film', 'film.png', '/fɪlm/', 'Bộ phim', 'noun', 'They watched a film about history last night.'),
        (25, 'Gallery', 'gallery.png', '/ˈgæləri/', 'Phòng trưng bày', 'noun', 'The gallery displays contemporary art.'),
        (25, 'Illustration', 'illustration.png', '/ˌɪləˈstreɪʃən/', 'Hình minh họa', 'noun', 'She created an illustration for the book cover.'),
        (25, 'Image', 'image.png', '/ˈɪmɪʤ/', 'Bức ảnh', 'noun', 'The photographer captured a beautiful image of the sunset.'),
        (25, 'Inspiration', 'inspiration.png', '/ˌɪnspəˈreɪʃən/', 'Nguồn cảm hứng', 'noun', 'Nature is a great source of inspiration for artists.'),
        (25, 'Inspire', 'inspire.png', '/ɪnˈspaɪr/', 'Truyền cảm hứng', 'verb', 'The teacher inspires students to pursue their passions.'),
        (25, 'Model', 'model.png', '/ˈmɑdəl/', 'Người mẫu', 'noun', 'She works as a model for fashion magazines.'),
        (25, 'Movie', 'movie.png', '/ˈmuvi/', 'Bộ phim', 'noun', 'They watched a comedy movie last weekend.'),
        (25, 'Music', 'music.png', '/ˈmjuzɪk/', 'Âm nhạc', 'noun', 'He loves listening to classical music in his free time.'),
        (25, 'Novel', 'novel.png', '/ˈnɑvəl/', 'Tiểu thuyết', 'noun', 'She wrote a novel about her travels around the world.'),
        (25, 'Performance', 'performance.png', '/pərˈfɔrməns/', 'Phần trình diễn', 'noun', 'The performance was outstanding and received great applause.'),
        (25, 'Photo', 'photo.png', '/ˈfoʊˌtoʊ/', 'Bức ảnh', 'noun', 'They took a photo at the beach during their vacation.'),
        (25, 'Photographer', 'photographer.png', '/fəˈtɑgrəfər/', 'Nhiếp ảnh gia', 'noun', 'The photographer captured beautiful portraits at the event.'),
        (25, 'Poem', 'poem.png', '/ˈpoʊəm/', 'Bài thơ', 'noun', 'She wrote a touching poem for her friend\'s birthday.'),
        (25, 'Poet', 'poet.png', '/ˈpoʊət/', 'Nhà thơ', 'noun', 'The poet is known for his deep and meaningful verses.'),
        (25, 'Portrait', 'portrait.png', '/ˈpɔrtrət/', 'Tranh chân dung', 'noun', 'The artist painted a stunning portrait of his grandmother.'),
        (25, 'Show', 'show.png', '/ʃoʊ/', 'Buổi biểu diễn', 'noun', 'They went to a Broadway show last month.'),
        (25, 'Singer', 'singer.png', '/ˈsɪŋər/', 'Ca sĩ', 'noun', 'She is a talented singer with a beautiful voice.'),
        (25, 'Sketch', 'sketch.png', '/skɛʧ/', 'Bản thảo, bản nháp', 'noun', 'The artist made a quick sketch of the landscape.'),
        (25, 'Studio', 'studio.png', '/ˈstudiˌoʊ/', 'Xưởng (vẽ, chụp ảnh, làm nhạc, làm phim)', 'noun', 'The photographer has a studio downtown.'),
        (25, 'Video', 'video.png', '/ˈvɪdioʊ/', 'Đoạn phim', 'noun', 'They watched a short video about wildlife conservation.'),
        (26, 'Company', 'company.png', '/ˈkʌmpəni/', 'Công ty', 'noun', 'The company is expanding into new markets.'),
        (26, 'Enterprise', 'enterprise.png', '/ˈentəpraɪz/', 'Tổ chức kinh doanh, xí nghiệp, hãng', 'noun', 'The enterprise focuses on innovative technology.'),
        (26, 'Corporation', 'corporation.png', '/kɔːpəˈreɪʃn/', 'Tập đoàn', 'noun', 'He works for a multinational corporation.'),
        (26, 'Holding company', 'holding_company.png', '/ˈhəʊldɪŋ ˈkʌmpəni/', 'Công ty mẹ', 'noun', 'The holding company owns several smaller businesses.'),
        (26, 'Subsidiary', 'subsidiary.png', '/səbˈsɪdiəri/', 'Công ty con', 'noun', 'The subsidiary company operates in a different industry.'),
        (26, 'Affiliate', 'affiliate.png', '/əˈfɪlieɪt/', 'Công ty liên kết', 'noun', 'They signed an agreement with an affiliate company to expand.'),
        (26, 'State-owned enterprise', 'state_owned.png', '/steɪt əʊn ˈentəpraɪz/', 'Công ty nhà nước', 'noun', 'The state-owned enterprise provides essential services.'),
        (26, 'Private company', 'private_company.png', '/ˈpraɪvət ˈkʌmpəni/', 'Công ty tư nhân', 'noun', 'The private company is focused on luxury products.'),
        (26, 'Partnership', 'partnership.png', '/ˈpɑːtnəʃɪp/', 'Công ty hợp doanh', 'noun', 'They formed a partnership to improve market reach.'),
        (26, 'Joint venture company', 'joint_venture.png', '/ˌdʒɔɪnt ˈventʃə(r)/', 'Công ty liên doanh', 'noun', 'The joint venture company focuses on renewable energy.'),
        (26, 'Limited company (Ltd)', 'limited_company.png', '/ˌlɪmɪtɪd ˈkʌmpəni/', 'Công ty trách nhiệm hữu hạn', 'noun', 'The limited company operates with a strict liability structure.'),
        (26, 'Joint stock company (JSC)', 'joint_stock.png', '/ˌdʒɔɪnt ˈstɒk kʌmpəni/', 'Công ty cổ phần', 'noun', 'The joint stock company raises capital through shares.'),
        (26, 'Marketing Department', 'marketing_department.png', '/‘ma:kitiη dɪˈpɑːrt.mənt/', 'Phòng Marketing, phòng tiếp thị', 'noun', 'The marketing department is launching a new campaign.'),
        (26, 'Sales Department', 'sales_department.png', '/seil dɪˈpɑːrt.mənt/', 'Phòng Kinh doanh', 'noun', 'The sales department met its quarterly targets.'),
        (26, 'Public Relations Department', 'pr_department.png', '/ˌpʌb.lɪk rɪˈleɪ.ʃənz dɪˈpɑːrt.mənt/', 'Phòng Quan hệ công chúng', 'noun', 'The public relations department is handling the company\'s image.'),
        (26, 'Administration Department', 'admin_department.png', '/ədˌmɪn.əˈstreɪ.ʃən dɪˈpɑːrt.mənt/', 'Phòng Hành chính', 'noun', 'The administration department manages the daily office tasks.'),
        (26, 'Human Resource Department', 'hr_department.png', '/‘hju:mən ri’sɔ:s dɪˈpɑːrt.mənt/', 'Phòng Nhân sự', 'noun', 'The human resource department is responsible for recruitment.'),
        (26, 'Training Department', 'training_department.png', '/‘treiniη dɪˈpɑːrt.mənt/', 'Phòng Đào tạo', 'noun', 'The training department offers workshops to improve skills.'),
        (26, 'Accounting Department', 'accounting_department.png', '/ə’kauntiη dɪˈpɑːrt.mənt/', 'Phòng Kế toán', 'noun', 'The accounting department oversees the company\'s finances.'),
        (26, 'Treasury Department', 'treasury_department.png', '/‘treʒəri dɪˈpɑːrt.mənt/', 'Phòng Ngân quỹ', 'noun', 'The treasury department manages cash flow and investments.'),
        (26, 'International Relations Department', 'international_relations.png', '/,intə’næ∫ənl rɪ.ˈleɪ.ʃən dɪˈpɑːrt.mənt/', 'Phòng Quan hệ quốc tế', 'noun', 'The international relations department handles global partnerships.'),
        (26, 'Local Payment Department', 'local_payment.png', '/ˈloʊ.kəl ˈpeɪ.mənt dɪˈpɑːrt.mənt/', 'Phòng Thanh toán trong nước', 'noun', 'The local payment department manages domestic transactions.'),
        (26, 'International Payment Department', 'international_payment.png', '/,intə’næ∫ənl ˈpeɪ.mənt dɪˈpɑːrt.mənt/', 'Phòng Thanh toán quốc tế', 'noun', 'The international payment department coordinates overseas transactions.'),
        (26, 'Information Technology Department', 'it_department.png', '/,infə’mei∫n tek’nɔlədʒi dɪˈpɑːrt.mənt/', 'Phòng Công nghệ thông tin', 'noun', 'The IT department supports the company\'s technology infrastructure.'),
        (26, 'Customer Service Department', 'customer_service.png', '/‘kʌstəmə ‘sə:vis dɪˈpɑːrt.mənt/', 'Phòng Chăm sóc khách hàng', 'noun', 'The customer service department handles client inquiries and issues.'),
        (26, 'Audit Department', 'audit_department.png', '/‘ɔ:dit dɪˈpɑːrt.mənt/', 'Phòng Kiểm toán', 'noun', 'The audit department ensures compliance with financial regulations.'),
        (26, 'Product Development Department', 'product_dev_department.png', '/‘prɔdəkt di’veləpmənt dɪˈpɑːrt.mənt/', 'Phòng Nghiên cứu và phát triển sản phẩm', 'noun', 'The product development department creates new offerings for the market.'),
        (27, 'Access', 'access.png', '/ˈækˌsɛs/', 'sự truy cập', 'noun', 'You need the correct credentials to gain access to the system.'),
        (27, 'Application', 'application.png', '/ˌæpləˈkeɪʃən/', 'ứng dụng trên điện thoại di động, máy tính bảng', 'noun', 'I downloaded a new application for photo editing.'),
        (27, 'Blog', 'blog.png', '/blɔg/', 'nhật ký trực tuyến', 'noun', 'She writes a daily blog about travel experiences.'),
        (27, 'Browser', 'browser.png', '/ˈbraʊzər/', 'trình duyệt', 'noun', 'Chrome is a popular browser for browsing the web.'),
        (27, 'Click', 'click.png', '/klɪk/', 'nhấp chuột', 'noun', 'Click on the link to open the website.'),
        (27, 'Computer', 'computer.png', '/kəmˈpjutər/', 'máy tính để bàn', 'noun', 'He works on a computer in the office every day.'),
        (27, 'Connection', 'connection.png', '/kəˈnɛkʃən/', 'kết nối', 'noun', 'The internet connection was slow this morning.'),
        (27, 'Data', 'data.png', '/ˈdeɪtə/', 'dữ liệu', 'noun', 'We need more data to analyze the trends.'),
        (27, 'Delete', 'delete.png', '/dɪˈlit/', 'xóa bỏ', 'verb', 'I accidentally deleted an important file.'),
        (27, 'Download', 'download.png', '/ˈdaʊnˌloʊd/', 'tải về, tải xuống', 'verb', 'You can download the software from the official website.'),
        (27, 'Ebook', 'ebook.png', '/i-bʊk/', 'sách điện tử', 'noun', 'She is reading an ebook on her tablet.'),
        (27, 'Email', 'email.png', '/i-meɪl/', 'thư điện tử', 'noun', 'I sent you an email with the attachment.'),
        (27, 'Error', 'error.png', '/ˈɛrər/', 'lỗi', 'noun', 'The program showed an error message.'),
        (27, 'File', 'file.png', '/faɪl/', 'tập tin', 'noun', 'The file was too large to send by email.'),
        (27, 'Folder', 'folder.png', '/ˈfoʊldər/', 'thư mục', 'noun', 'You should organize your files into folders for easy access.'),
        (27, 'Hardware', 'hardware.png', '/ˈhɑrˌdwɛr/', 'phần cứng', 'noun', 'The hardware of the computer is outdated.'),
        (27, 'Headphone', 'headphone.png', '/ˈhɛdˌfoʊn/', 'tai nghe', 'noun', 'I listen to music with my wireless headphones.'),
        (27, 'Install', 'install.png', '/ɪnˈstɔl/', 'cài đặt, lắp đặt', 'verb', 'You need to install the app before using it.'),
        (27, 'Internet', 'internet.png', '/ˈɪntərˌnɛt/', 'mạng internet', 'noun', 'The internet is essential for remote work.'),
        (27, 'Keyboard', 'keyboard.png', '/ˈkiˌbɔrd/', 'bàn phím máy tính', 'noun', 'My keyboard is wireless and very comfortable.'),
        (27, 'Laptop', 'laptop.png', '/ˈlæpˌtɑp/', 'máy tính xách tay', 'noun', 'I need a new laptop for my studies.'),
        (27, 'Link', 'link.png', '/lɪŋk/', 'đường dẫn', 'noun', 'I sent you a link to the article.'),
        (27, 'Log in', 'login.png', '/lɔg ɪn/', 'đăng nhập', 'noun', 'You need to log in to your account to access the features.'),
        (27, 'Mouse', 'mouse.png', '/maʊs/', 'chuột máy tính', 'noun', 'The mouse is not responding properly.'),
        (27, 'Password', 'password.png', '/ˈpæˌswɜrd/', 'mật khẩu', 'noun', 'Change your password regularly for security reasons.'),
        (27, 'Program', 'program.png', '/ˈproʊˌgræm/', 'chương trình máy tính', 'noun', 'The program has many useful features.'),
        (27, 'Sign up', 'signup.png', '/saɪn ʌp/', 'đăng ký', 'noun', 'You need to sign up for an account to participate in the event.'),
        (27, 'Smartphone', 'smartphone.png', '/smärtˌfōn/', 'điện thoại thông minh', 'noun', 'She uses her smartphone for online shopping.'),
        (27, 'Social network', 'social_network.png', '/ˈsoʊʃəl ˈnɛˌtwɜrk/', 'mạng xã hội', 'noun', 'Many people use social networks to stay connected.'),
        (27, 'Software', 'software.png', '/ˈsɔfˌtwɛr/', 'phần mềm', 'noun', 'You need to update your software for the latest features.'),
        (27, 'Speaker', 'speaker.png', '/ˈspikər/', 'loa', 'noun', 'The speaker produces excellent sound quality.'),
        (27, 'Surf', 'surf.png', '/sɜrf/', 'lướt (web)', 'verb', 'I love to surf the internet in my free time.'),
        (27, 'System', 'system.png', '/ˈsɪstəm/', 'hệ thống', 'noun', 'The computer system crashed due to a technical issue.'),
        (27, 'Tablet', 'tablet.png', '/ˈtæblət/', 'máy tính bảng', 'noun', 'She uses a tablet to read books and watch movies.'),
        (27, 'Virus', 'virus.png', '/ˈvaɪrəs/', 'vi rút', 'noun', 'The computer was infected by a virus and stopped working.'),
        (27, 'Wifi', 'wifi.png', '/Wīfī/', 'mạng wifi', 'noun', 'The wifi signal is very strong in this area.'),
        (27, 'Wireless', 'wireless.png', '/ˈwaɪrlɪs/', 'không dây', 'adj', 'I prefer wireless devices for convenience.'),
        (28, 'Answer', 'answer.png', '/ˈænsər/', 'trả lời', 'verb', 'Please answer the phone when it rings.'),
        (28, 'Call', 'call.png', '/kɔl/', 'gọi điện thoại', 'verb', 'I need to call my friend to confirm the details.'),
        (28, 'Cellphone', 'cellphone.png', '/ˈsɛlfoʊn/', 'điện thoại di động', 'noun', 'She uses her cellphone to stay in touch with her family.'),
        (28, 'Communicate', 'communicate.png', '/kəmˈjunəˌkeɪt/', 'giao tiếp', 'verb', 'They communicate through emails and phone calls.'),
        (28, 'Contact', 'contact.png', '/ˈkɑnˌtækt/', 'liên hệ; (n) địa chỉ liên hệ', 'verb', 'You can contact me via email or phone.'),
        (28, 'Hotline', 'hotline.png', '/ˈhɑtˌlaɪn/', 'đường dây nóng', 'noun', 'The company offers a 24/7 hotline for customer support.'),
        (28, 'Message', 'message.png', '/ˈmɛsəʤ/', 'tin nhắn', 'noun', 'I received a message from my colleague this morning.'),
        (28, 'Missed', 'missed.png', '/mɪst/', 'lỡ, nhỡ', 'verb', 'I missed your call, can you call me back?'),
        (28, 'Phone number', 'phone_number.png', '/foʊn ˈnʌmbər/', 'số điện thoại', 'noun', 'Please leave your phone number so I can contact you later.'),
        (28, 'Receive', 'receive.png', '/rəˈsiv/', 'nhận được', 'verb', 'Did you receive my email yesterday?'),
        (28, 'Send', 'send.png', '/sɛnd/', 'gửi đi', 'verb', 'I will send the documents via email.'),
        (28, 'Signature', 'signature.png', '/ˈsɪgnəʧər/', 'chữ ký', 'noun', 'You need to sign your name at the bottom of the document.'),
        (28, 'Stamp', 'stamp.png', '/stæmp/', 'tem', 'noun', 'I need to buy a stamp to send the letter.'),
        (28, 'Text', 'text.png', '/tɛkst/', 'nhắn tin; tin nhắn (n)', 'verb', 'I will text you the address shortly.'),
        (29, 'Advertisement', 'advertisement.png', '/ˌædvərˈtaɪzmənt/', 'quảng cáo', 'noun', 'The advertisement on TV was very catchy.'),
        (29, 'Article', 'article.png', '/ˈɑrtɪkəl/', 'bài báo', 'noun', 'I read an interesting article about technology.'),
        (29, 'Broadcast', 'broadcast.png', '/ˈbrɔdˌkæst/', 'phát sóng; (n) chương trình phát sóng', 'verb', 'The news broadcast is on every evening at 7 PM.'),
        (29, 'Cable', 'cable.png', '/ˈkeɪbəl/', 'dây cáp, truyền hình cáp', 'noun', 'We have a cable TV subscription to watch more channels.'),
        (29, 'Channel', 'channel.png', '/ˈʧænəl/', 'kênh truyền hình', 'noun', 'I switched to another channel to watch my favorite show.'),
        (29, 'Character', 'character.png', '/ˈkɛrɪktər/', 'nhân vật', 'noun', 'The main character of the movie is a detective.'),
        (29, 'Column', 'column.png', '/ˈkɑləm/', 'chuyên mục', 'noun', 'She writes a weekly column about travel.'),
        (29, 'Commercial', 'commercial.png', '/kəˈmɜrʃəl/', 'quảng cáo', 'noun', 'The commercial was about a new brand of coffee.'),
        (29, 'Daily', 'daily.png', '/ˈdeɪli/', 'hằng ngày', 'noun', 'I read the daily newspaper every morning.'),
        (29, 'Editor', 'editor.png', '/ˈɛdətər/', 'biên tập viên', 'noun', 'The editor made several changes to the article before publishing it.'),
        (29, 'Episode', 'episode.png', '/ˈɛpəˌsoʊd/', 'phần, tập (phim, chương trình)', 'noun', 'The latest episode of the series aired last night.'),
        (29, 'Headline', 'headline.png', '/ˈhɛˌdlaɪn/', 'tiêu đề', 'noun', 'The headline of the newspaper caught my attention immediately.'),
        (29, 'Issue', 'issue.png', '/ˈɪʃu/', 'số, kỳ phát hành', 'noun', 'This is the latest issue of the magazine.'),
        (29, 'Live', 'live.png', '/lɪv/', 'truyền hình trực tiếp', 'noun', 'The live broadcast of the concert was amazing.'),
        (29, 'Magazine', 'magazine.png', '/ˈmægəˌzin/', 'tạp chí', 'noun', 'She subscribed to a fashion magazine.'),
        (29, 'Newspaper', 'newspaper.png', '/ˈnuzˌpeɪpər/', 'báo giấy', 'noun', 'I like to read the newspaper with my morning coffee.'),
        (29, 'Publisher', 'publisher.png', '/ˈpʌblɪʃər/', 'nhà xuất bản', 'noun', 'The publisher is planning to release a new edition next month.'),
        (29, 'Reporter', 'reporter.png', '/rɪˈpɔrtər/', 'phóng viên', 'noun', 'The reporter interviewed the CEO for the evening news.'),
        (29, 'Script', 'script.png', '/skrɪpt/', 'kịch bản', 'noun', 'The script for the movie was written by a famous screenwriter.'),
        (29, 'Subtitle', 'subtitle.png', '/ˈsʌbˌtaɪtəl/', 'phụ đề', 'noun', 'The film has English subtitles for international viewers.'),
        (15, 'Miniskirt', 'miniskirt.png', '/mɪniskɜːt/', 'Chân váy ngắn', 'noun', 'She loves wearing a miniskirt during the summer.'),
        (15, 'Dress', 'dress.png', '/dres/', 'Váy liền thân', 'noun', 'She wore a beautiful dress to the party.'),
        (15, 'Blouse', 'blouse.png', '/blaʊz/', 'Áo sơ mi nữ', 'noun', 'This blouse matches well with the skirt.'),
        (15, 'Skirt', 'skirt.png', '/skɜːt/', 'Chân váy', 'noun', 'She bought a new skirt for the meeting.'),
        (15, 'Evening dress', 'evening_dress.png', '/i’vniη dres/', 'Váy dạ hội', 'noun', 'She looked stunning in her evening dress.'),
        (15, 'Summer dress', 'summer_dress.png', '/’sʌmə dres/', 'Váy mùa hè', 'noun', 'This summer dress is perfect for the hot weather.'),
        (15, 'Wool dress', 'wool_dress.png', '/wul dres/', 'Váy len', 'noun', 'A wool dress keeps you warm in winter.'),
        (15, 'Pinafore dress', 'pinafore_dress.png', '/’pinəfɔdres/', 'Váy sát nách', 'noun', 'She prefers wearing a pinafore dress to work.'),
        (15, 'Pleated skirt', 'pleated_skirt.png', '/plit kət/', 'Váy xếp ly', 'noun', 'A pleated skirt is a timeless fashion piece.'),
        (15, 'Slacks', 'slacks.png', '/slæk/', 'Váy rộng xoè', 'noun', 'She chose slacks for a comfortable evening.'),
        (15, 'Sheath dress', 'sheath_dress.png', '/ʃiːθ dres/', 'Váy bút chì', 'noun', 'The sheath dress highlighted her figure beautifully.'),
        (15, 'Straight dress', 'straight_dress.png', '/streɪt dres/', 'Váy suông', 'noun', 'A straight dress is ideal for a casual look.'),
        (15, 'Ruffled dress', 'ruffled_dress.png', '/rʌfld dres/', 'Váy xếp tầng', 'noun', 'The ruffled dress made her look elegant and chic.'),
        (16, 'Shop', 'shop.png', '/ʃɑp/', 'Cửa tiệm', 'noun', 'She bought a new jacket at the shop downtown.'),
        (16, 'Shop window', 'shop_window.png', '/’wɪndoʊ/', 'Cửa kính trưng bày', 'noun', 'The shop window displayed beautiful dresses.'),
        (16, 'Shop assistant', 'shop_assistant.png', '/ə’sɪstənt/', 'Nhân viên bán hàng', 'noun', 'The shop assistant helped me find the perfect size.'),
        (16, 'Cashier', 'cashier.png', '/kæˈʃɪr/', 'Nhân viên thu ngân', 'noun', 'I paid at the cashier before leaving the store.'),
        (16, 'Aisle', 'aisle.png', '/aɪl/', 'Quầy hàng', 'noun', 'The aisle was full of customers looking for bargains.'),
        (16, 'Shopping bag', 'shopping_bag.png', '/’ʃɑpɪŋ/ /bæɡ/', 'Túi mua sắm', 'noun', 'She packed all her purchases in a shopping bag.'),
        (16, 'Trolley', 'trolley.png', '/’trɑli/', 'Xe đẩy mua sắm', 'noun', 'She filled the trolley with groceries at the supermarket.'),
        (16, 'Plastic bag', 'plastic_bag.png', '/’plæstɪk/ /bæɡ/', 'Túi nilon', 'noun', 'They gave me a plastic bag for my groceries.'),
        (16, 'Stockroom', 'stockroom.png', '/’stɑk,rum/', 'Nhà kho', 'noun', 'The stockroom is where all the extra inventory is kept.'),
        (16, 'Counter', 'counter.png', '/’kaʊntər/', 'Quầy tính tiền', 'noun', 'Please proceed to the counter to pay for your items.'),
        (16, 'Fitting room', 'fitting_room.png', '/’fɪtɪŋ/ /rum/', 'Phòng thử đồ', 'noun', 'She went to the fitting room to try on the dress.'),
        (16, 'Shopping list', 'shopping_list.png', '/lɪst/', 'Danh sách mua sắm', 'noun', 'I made a shopping list before going to the store.'),
        (16, 'Special offer', 'special_offer.png', '/ˈspeʃlˈɔːfər/', 'Ưu đãi đặc biệt', 'noun', 'The shop has a special offer on all winter coats.'),
        (16, 'Price', 'price.png', '/praɪs/', 'Giá cả', 'noun', 'The price of the shoes was reduced during the sale.'),
        (16, 'Queue', 'queue.png', '/kju/', 'Xếp hàng', 'verb', 'We had to queue for an hour to get the tickets.'),
        (16, 'Brand', 'brand.png', '/brænd/', 'Thương hiệu', 'noun', 'Nike is a popular brand for sports shoes.'),
        (16, 'Sample', 'sample.png', '/’sæmpəl/', 'Hàng mẫu', 'noun', 'The store offered free samples of their new perfume.'),
        (16, 'Leaflet', 'leaflet.png', '/’liflɪt/', 'Tờ rơi', 'noun', 'She handed me a leaflet about the upcoming sale.'),
        (16, 'Billboard', 'billboard.png', '/’bɪl,boʊrd/', 'Biển quảng cáo', 'noun', 'The billboard on the highway advertised a new restaurant.'),
        (16, 'Catchphrase', 'catchphrase.png', '/’kæt∫freiz/', 'Câu khẩu hiệu', 'noun', 'The advertisement included a catchy catchphrase.'),
        (16, 'Customer', 'customer.png', '/ˈkʌstəmər/', 'Khách hàng', 'noun', 'The customer was satisfied with the service.'),
        (16, 'Complaint', 'complaint.png', '/kəmˈpleɪnt/', 'Phàn nàn', 'verb', 'He made a complaint about the poor service at the restaurant.'),
        (16, 'Order', 'order.png', '/ɔːrdər/', 'Đặt hàng', 'verb', 'I placed an order for a pizza online.'),
        (16, 'Sell', 'sell.png', '/sel/', 'Bán', 'verb', 'They sell fresh vegetables at the market every day.'),
        (16, 'Buy', 'buy.png', '/baɪ/', 'Mua', 'verb', 'I will buy a new phone next week.'),
        (16, 'Price tag', 'price_tag.png', '/ˈpraɪs tæɡ/', 'Nhãn giá', 'noun', 'The price tag on the jacket was $50.'),
        (16, 'Shopaholic', 'shopaholic.png', '/ˌʃɑːpəˈhɑːlɪk/', 'Người nghiện mua sắm', 'noun', 'She is a shopaholic who loves to buy clothes.'),
        (16, 'Expiration', 'expiration.png', '/,ekspə’rei∫n/', 'Hạn sử dụng', 'noun', 'Make sure to check the expiration date on the product before buying.'),
        (14, 'Build things', 'build_things.png', '/bɪld θɪŋz/', 'Chơi xếp hình', 'verb', 'Kids love to build things with blocks.'),
        (14, 'Chat with friends', 'chat_with_friends.png', '/ʧæt wɪð frɛndz/', 'Tán gẫu với bạn bè', 'verb', 'She enjoys chatting with friends online.'),
        (14, 'Collect stamp', 'collect_stamp.png', '/kəˈlɛkt stæmp/', 'Sưu tập tem', 'verb', 'My brother likes to collect stamps from different countries.'),
        (14, 'Do magic tricks', 'do_magic_tricks.png', '/duː ˈmæʤɪk trɪks/', 'Làm ảo thuật', 'verb', 'He can do amazing magic tricks.'),
        (14, 'Do sports', 'do_sports.png', '/duː spɔːts/', 'Chơi thể thao', 'verb', 'Doing sports is good for your health.'),
        (14, 'Explore', 'explore.png', '/ɪksˈplɔ/', 'Đi thám hiểm', 'verb', 'They love to explore new places.'),
        (14, 'Fly kites', 'fly_kites.png', '/flaɪ kaɪts/', 'Thả diều', 'verb', 'The children are flying kites in the park.'),
        (14, 'Go camping', 'go_camping.png', '/gəʊ ˈkæmpɪŋ/', 'Đi cắm trại', 'verb', 'We plan to go camping this weekend.'),
        (14, 'Go for a walk', 'go_for_a_walk.png', '/gəʊ fɔːr ə wɔːk/', 'Đi dạo', 'verb', 'She goes for a walk every morning.'),
        (14, 'Go partying', 'go_partying.png', '/gəʊ ˈpɑːtɪɪŋ/', 'Dự tiệc', 'verb', 'They often go partying on Friday nights.'),
        (14, 'Go shopping', 'go_shopping.png', '/gəʊ ˈʃɒpɪŋ/', 'Đi mua sắm', 'verb', 'She loves to go shopping with her friends.'),
        (14, 'Go skateboarding', 'go_skateboarding.png', '/gəʊ ˈskeɪtbɔːdɪŋ/', 'Trượt ván', 'verb', 'He is learning how to go skateboarding.'),
        (14, 'Go swimming', 'go_swimming.png', '/gəʊ ˈswɪmɪŋ/', 'Đi bơi', 'verb', 'They go swimming every weekend.'),
        (14, 'Hang out with friends', 'hang_out_with_friends.png', '/hæŋ aʊt wɪð frɛndz/', 'Đi chơi với bạn', 'verb', 'He likes to hang out with friends after school.'),
        (14, 'Jogging', 'jogging.png', '/ˈdʒɑː.ɡɪŋ/', 'Chạy bộ', 'verb', 'She goes jogging every morning.'),
        (14, 'Knit', 'knit.png', '/nɪt/', 'Đan lát', 'verb', 'My grandmother loves to knit scarves.'),
        (14, 'Listen to music', 'listen_to_music.png', '/ˈlɪsn tuː ˈmjuːzɪk/', 'Nghe nhạc', 'verb', 'I enjoy listening to music while working.'),
        (14, 'Mountaineering', 'mountaineering.png', '/ˌmaʊn.tənˈɪr.ɪŋ/', 'Đi leo núi', 'verb', 'They love mountaineering in the Himalayas.'),
        (14, 'Play an instrument', 'play_an_instrument.png', '/pleɪ ən ˈɪnstrʊmənt/', 'Chơi nhạc cụ', 'verb', 'She can play several instruments.'),
        (14, 'Play chess', 'play_chess.png', '/pleɪ ʧɛs/', 'Chơi cờ', 'verb', 'My dad and I often play chess together.'),
        (14, 'Play computer games', 'play_computer_games.png', '/pleɪ kəmˈpjuːtə geɪmz/', 'Chơi game', 'verb', 'He spends hours playing computer games.'),
        (14, 'Read books', 'read_books.png', '/riːd bʊks/', 'Đọc sách', 'verb', 'She loves to read books in her free time.'),
        (14, 'Sing', 'sing.png', '/sɪŋ/', 'Hát', 'verb', 'He enjoys singing karaoke.'),
        (14, 'Surf net', 'surf_net.png', '/sɜːf nɛt/', 'Lướt net', 'verb', 'I often surf the net for new recipes.'),
        (14, 'Take photo', 'take_photo.png', '/teɪk ˈfəʊtəʊ/', 'Chụp ảnh', 'verb', 'She likes to take photos of nature.'),
        (14, 'To the cinema', 'to_the_cinema.png', '/gəʊ tuː ðə ˈsɪnəmə/', 'Đi xem phim', 'verb', 'They are going to the cinema tonight.'),
        (14, 'Travel', 'travel.png', '/ˈtræv.əl/', 'Du lịch', 'verb', 'I dream of traveling around the world.'),
        (14, 'Watch television', 'watch_television.png', '/wɒʧ ˈtɛlɪˌvɪʒən/', 'Xem tivi', 'verb', 'We watch television every evening.'),
        (13, 'Mother', 'mother.png', '/ˈmʌðər/', 'Mẹ', 'noun', 'My mother is a teacher.'),
        (13, 'Father', 'father.png', '/ˈfɑːðər/', 'Bố', 'noun', 'His father works in a factory.'),
        (13, 'Husband', 'husband.png', '/ˈhʌzbənd/', 'Chồng', 'noun', 'Her husband is very supportive.'),
        (13, 'Wife', 'wife.png', '/waɪf/', 'Vợ', 'noun', 'He loves his wife dearly.'),
        (13, 'Daughter', 'daughter.png', '/ˈdɔːtə(r)/', 'Con gái', 'noun', 'Their daughter is in college.'),
        (13, 'Son', 'son.png', '/sʌn/', 'Con trai', 'noun', 'My son enjoys playing soccer.'),
        (13, 'Parent', 'parent.png', '/ˈpeərənt/', 'Bố mẹ', 'noun', 'Every parent wants the best for their child.'),
        (13, 'Grandparent', 'grandparent.png', '/ˈɡrænpeərənt/', 'Ông bà', 'noun', 'I love visiting my grandparents.'),
        (13, 'Uncle', 'uncle.png', '/ˈʌŋkl/', 'Bác trai/cậu/chú', 'noun', 'My uncle lives in New York.'),
        (13, 'Aunt', 'aunt.png', '/ɑːnt/', 'Bác gái/cô/dì', 'noun', 'My aunt baked a cake for my birthday.'),
        (13, 'Cousin', 'cousin.png', '/ˈkʌzn/', 'Anh/chị/em họ', 'noun', 'I spent the summer with my cousin.'),
        (13, 'Mother-in-law', 'mother_in_law.png', '/ˈmʌðər ɪnˌlɔ/', 'Mẹ chồng/mẹ vợ', 'noun', 'She has a great relationship with her mother-in-law.'),
        (13, 'Son-in-law', 'son_in_law.png', '/ˈsʌn ɪn lɔ/', 'Con rể', 'noun', 'Her son-in-law is very polite.'),
        (13, 'Daughter-in-law', 'daughter_in_law.png', '/ˈdɔt̮ər ɪn lɔ/', 'Con dâu', 'noun', 'Their daughter-in-law is a doctor.'),
        (12, 'Afraid', 'afraid.png', '/əˈfreɪd/', 'Lo sợ, sợ hãi', 'adj', 'She was afraid of the dark.'),
        (12, 'Angry', 'angry.png', '/ˈæŋgri/', 'Tức giận, giận dữ', 'adj', 'He was angry about the delay.'),
        (12, 'Bored', 'bored.png', '/bɔrd/', 'Chán nản', 'adj', 'The lecture made him bored.'),
        (12, 'Confused', 'confused.png', '/kənˈfjuzd/', 'Bối rối, lúng túng', 'adj', 'I am confused by the instructions.'),
        (12, 'Disappointed', 'disappointed.png', '/ˌdɪsəˈpɔɪntɪd/', 'Thất vọng', 'adj', 'She felt disappointed with the result.'),
        (12, 'Disgusted', 'disgusted.png', '/dɪsˈgʌstɪd/', 'Kinh tởm', 'noun', 'He was disgusted by the smell.'),
        (12, 'Embarrassed', 'embarrassed.png', '/ɪmˈbɛrəst/', 'Xấu hổ, ngại ngùng', 'adj', 'She felt embarrassed about her mistake.'),
        (12, 'Excited', 'excited.png', '/ɪkˈsaɪtəd/', 'Hứng thú, hào hứng', 'adj', 'I am excited about the trip.'),
        (12, 'Fear', 'fear.png', '/fɪr/', 'Nỗi sợ hãi', 'adj', 'He couldn’t hide his fear of spiders.'),
        (12, 'Guilty', 'guilty.png', '/ˈgɪlti/', 'Cảm thấy tội lỗi', 'adj', 'She felt guilty about lying.'),
        (12, 'Happy', 'happy.png', '/ˈhæpi/', 'Vui vẻ, hạnh phúc', 'adj', 'He is happy with his new job.'),
        (12, 'Hungry', 'hungry.png', '/ˈhʌŋgri/', 'Đói', 'adj', 'I am very hungry after the workout.'),
        (12, 'Lonely', 'lonely.png', '/ˈloʊnli/', 'Cô đơn', 'adj', 'She felt lonely in the new city.'),
        (12, 'Nervous', 'nervous.png', '/ˈnɜrvəs/', 'Lo lắng', 'adj', 'He was nervous before the interview.'),
        (12, 'Sad', 'sad.png', '/sæd/', 'Buồn bã', 'adj', 'She felt sad after hearing the news.'),
        (12, 'Sick', 'sick.png', '/sɪk/', 'Ốm yếu, ốm', 'adj', 'He is sick with the flu.'),
        (12, 'Surprised', 'surprised.png', '/sərˈpraɪzd/', 'Ngạc nhiên', 'adj', 'I was surprised by his reaction.'),
        (12, 'Thirsty', 'thirsty.png', '/ˈθɜrsti/', 'Khát', 'adj', 'I am thirsty after the long run.'),
        (12, 'Tired', 'tired.png', '/ˈtaɪərd/', 'Mệt mỏi', 'adj', 'She felt tired after working all day.'),
        (12, 'Worried', 'worried.png', '/ˈwɜrid/', 'Lo lắng', 'adj', 'He is worried about his exams.'),
        (11, 'Brave', 'brave.png', '/breɪv/', 'Can đảm, dũng cảm', 'adj', 'The firefighter is very brave.'),
        (11, 'Cheerful', 'cheerful.png', '/ˈʧɪrfəl/', 'Sôi nổi, vui tươi', 'adj', 'She has a cheerful attitude.'),
        (11, 'Clever', 'clever.png', '/ˈklɛvər/', 'Thông minh, khôn khéo', 'adj', 'The clever boy solved the puzzle quickly.'),
        (11, 'Confident', 'confident.png', '/ˈkɑnfədənt/', 'Tự tin', 'adj', 'He is confident about his skills.'),
        (11, 'Easy-going', 'easy_going.png', '/ˈizi-ˈgoʊɪŋ/', 'Thoải mái', 'adj', 'She has an easy-going personality.'),
        (11, 'Energetic', 'energetic.png', '/ɛnərˈʤɛtɪk/', 'Tràn đầy năng lượng', 'adj', 'He is an energetic student.'),
        (11, 'Friendly', 'friendly.png', '/ˈfrɛndli/', 'Thân thiện', 'adj', 'She is very friendly to everyone.'),
        (11, 'Funny', 'funny.png', '/ˈfʌni/', 'Hài hước, vui tính', 'adj', 'He always tells funny jokes.'),
        (11, 'Generous', 'generous.png', '/ˈʤɛnərəs/', 'Hào phóng', 'adj', 'She is very generous with her money.'),
        (11, 'Grumpy', 'grumpy.png', '/ˈgrʌmpi/', 'Cáu kỉnh, khó chịu', 'adj', 'He feels grumpy in the morning.'),
        (11, 'Hard-working', 'hard_working.png', '/hɑrd-ˈwɜrkɪŋ/', 'Siêng năng, chăm chỉ', 'adj', 'The hard-working student finished all his homework.'),
        (11, 'Honest', 'honest.png', '/ˈɑnəst/', 'Thật thà, trung thực', 'adj', 'She is honest about her feelings.'),
        (11, 'Kind', 'kind.png', '/kaɪnd/', 'Tử tế, tốt bụng', 'adj', 'He is always kind to animals.'),
        (11, 'Lazy', 'lazy.png', '/ˈleɪzi/', 'Lười biếng', 'adj', 'The lazy cat sleeps all day.'),
        (11, 'Loyal', 'loyal.png', '/ˈlɔɪəl/', 'Trung thành', 'adj', 'The dog is loyal to its owner.'),
        (11, 'Nice', 'nice.png', '/naɪs/', 'Tốt', 'adj', 'She is a nice person to work with.'),
        (11, 'Polite', 'polite.png', '/pəˈlaɪt/', 'Lịch sự, lễ phép', 'adj', 'He is polite to everyone.'),
        (11, 'Quiet', 'quiet.png', '/ˈkwaɪət/', 'Im lặng, trầm tính', 'adj', 'The library is a quiet place.'),
        (11, 'Selfish', 'selfish.png', '/ˈsɛlfɪʃ/', 'Ích kỷ', 'adj', 'Don’t be selfish, share your toys!'),
        (11, 'Shy', 'shy.png', '/ʃaɪ/', 'Nhút nhát, rụt rè', 'adj', 'He is too shy to speak in public.'),
        (10, 'Attractive', 'attractive.png', '/əˈtræktɪv/', 'Quyến rũ, hấp dẫn', 'adj', 'She has an attractive smile.'),
        (10, 'Beautiful', 'beautiful.png', '/ˈbjutəfəl/', 'Xinh đẹp, đẹp', 'adj', 'The sunset is beautiful.'),
        (10, 'Body shape', 'body_shape.png', '/ˈbɑdi ʃeɪp/', 'Vóc dáng, thân hình', 'noun', 'She has a nice body shape.'),
        (10, 'Charming', 'charming.png', '/ˈʧɑrmɪŋ/', 'Quyến rũ, thu hút', 'adj', 'He is a charming host.'),
        (10, 'Cute', 'cute.png', '/Kjut/', 'Đáng yêu, dễ thương', 'adj', 'The baby looks so cute.'),
        (10, 'Fat', 'fat.png', '/fæt/', 'Thừa cân, béo', 'adj', 'He is a bit fat.'),
        (10, 'Feature', 'feature.png', '/ˈfiʧər/', 'Đặc điểm, nét nổi bật', 'noun', 'Her eyes are her best feature.'),
        (10, 'Fit', 'fit.png', '/fɪt/', 'Cân đối, gọn gàng', 'adj', 'He stays fit by exercising daily.'),
        (10, 'Good-looking', 'good_looking.png', '/gʊd-ˈlʊkɪŋ/', 'Ưa nhìn, sáng sủa', 'adj', 'She is a good-looking actress.'),
        (10, 'Handsome', 'handsome.png', '/gʊd-ˈlʊkɪŋ/', 'Đẹp trai', 'adj', 'He is a handsome young man.'),
        (10, 'Height', 'height.png', '/haɪt/', 'Chiều cao', 'noun', 'What is your height?'),
        (10, 'Look', 'look.png', '/lʊk/', 'Vẻ ngoài', 'noun', 'His look is very stylish.'),
        (10, 'Lovely', 'lovely.png', '/ˈlʌvli/', 'Đáng yêu', 'adj', 'She has a lovely personality.'),
        (10, 'Muscular', 'muscular.png', '/ˈmʌskjələr/', 'Cơ bắp, lực lưỡng', 'adj', 'He is tall and muscular.'),
        (10, 'Pretty', 'pretty.png', '/ˈprɪti/', 'Xinh xắn', 'adj', 'She looks pretty in that dress.'),
        (10, 'Short', 'short.png', '/ʃɔrt/', 'Thấp', 'adj', 'He is short but very strong.'),
        (10, 'Tall', 'tall.png', '/tɔl/', 'Cao', 'adj', 'She is tall for her age.'),
        (10, 'Thin', 'thin.png', '/θɪn/', 'Gầy', 'adj', 'He is very thin after the illness.'),
        (10, 'Ugly', 'ugly.png', '/ˈʌgli/', 'Xấu xí', 'adj', 'The painting is ugly.'),
        (10, 'Weight', 'weight.png', '/weɪt/', 'Cân nặng', 'noun', 'He wants to lose some weight.'),
        (1, 'Hello', 'hello.png', '/həˈloʊ/', 'Xin chào', 'noun', 'Hello Jenny, have a good day!'),
        (1, 'Goodbye', 'goodbye.png', '/ɡʊdˈbaɪ/', 'Tạm biệt', 'noun', 'Bye Tom, see you later!'),
        (2, 'Computer', 'computer.png', '/kəmˈpjuː.tər/', 'Máy tính', 'noun', 'A good computer'),
        (9, 'Arm', 'arm.png', '/ɑrm/', 'Cánh tay', 'noun', 'She raised her arm.'),
        (9, 'Back', 'back.png', '/bæk/', 'Lưng', 'noun', 'He has pain in his back.'),
        (9, 'Belly', 'belly.png', '/ˈbɛli/', 'Bụng', 'noun', 'The baby touched his belly.'),
        (9, 'Blood', 'blood.png', '/blʌd/', 'Máu', 'noun', 'Blood flows through veins.'),
        (9, 'Body', 'body.png', '/ˈbɑdi/', 'Cơ thể', 'noun', 'The body needs exercise.'),
        (9, 'Body part', 'body_part.png', '/ˈbɑdi pɑrt/', 'Bộ phận cơ thể', 'noun', 'Name each body part.'),
        (9, 'Bone', 'bone.png', '/boʊn/', 'Xương', 'noun', 'He broke a bone in his hand.'),
        (9, 'Bottom', 'bottom.png', '/ˈbɑtəm/', 'Mông', 'noun', 'She sat on her bottom.'),
        (9, 'Brain', 'brain.png', '/breɪn/', 'Não', 'noun', 'The brain is complex.'),
        (9, 'Chest', 'chest.png', '/ʧɛst/', 'Ngực, lồng ngực', 'noun', 'He felt pain in his chest.'),
        (9, 'Ear', 'ear.png', '/Ir/', 'Tai', 'noun', 'The child covered her ears.'),
        (9, 'Eye', 'eye.png', '/aɪ/', 'Mắt', 'noun', 'She has blue eyes.'),
        (9, 'Face', 'face.png', '/feɪs/', 'Khuôn mặt', 'noun', 'His face turned red.'),
        (9, 'Finger', 'finger.png', '/ˈfɪŋgər/', 'Ngón tay', 'noun', 'She cut her finger.'),
        (9, 'Foot', 'foot.png', '/fʊt/', 'Bàn chân', 'noun', 'My foot hurts.'),
        (9, 'Hair', 'hair.png', '/hɛr/', 'Tóc', 'noun', 'She combed her hair.'),
        (9, 'Hand', 'hand.png', '/hænd/', 'Bàn tay', 'noun', 'He raised his hand.'),
        (9, 'Head', 'head.png', '/hɛd/', 'Đầu', 'noun', 'He hit his head.'),
        (9, 'Heart', 'heart.png', '/hɑrt/', 'Trái tim', 'noun', 'The heart pumps blood.'),
        (9, 'Hip', 'hip.png', '/hɪp/', 'Hông', 'noun', 'She swayed her hips.'),
        (9, 'Leg', 'leg.png', '/lɛg/', 'Chân', 'noun', 'Her leg was injured.'),
        (9, 'Lip', 'lip.png', '/lɪp/', 'Môi', 'noun', 'He bit his lip.'),
        (9, 'Mouth', 'mouth.png', '/maʊθ/', 'Miệng', 'noun', 'Open your mouth wide.'),
        (9, 'Neck', 'neck.png', '/nɛk/', 'Cổ', 'noun', 'She wore a scarf around her neck.'),
        (9, 'Nose', 'nose.png', '/noʊz/', 'Mũi', 'noun', 'He blew his nose.'),
        (9, 'Shoulder', 'shoulder.png', '/ˈʃoʊldər/', 'Vai', 'noun', 'He shrugged his shoulders.'),
        (9, 'Skin', 'skin.png', '/skɪn/', 'Làn da', 'noun', 'Her skin is soft.'),
        (9, 'Thigh', 'thigh.png', '/θaɪ/', 'Đùi', 'noun', 'He injured his thigh.'),
        (9, 'Toe', 'toe.png', '/toʊ/', 'Ngón chân', 'noun', 'She stubbed her toe.'),
        (9, 'Tongue', 'tongue.png', '/tʌŋ/', 'Lưỡi', 'noun', 'Stick out your tongue.'),
        (9, 'Tooth', 'tooth.png', '/tuθ/', 'Răng', 'noun', 'He brushed his teeth.'),
        (9, 'Waist', 'waist.png', '/weɪst/', 'Vòng eo, eo', 'noun', 'She tied a belt around her waist.'),
        (1, 'Hello', 'hello.png', '/həˈloʊ/', 'Xin chào'),
        (1, 'Goodbye', 'goodbye.png', '/ɡʊdˈbaɪ/', 'Tạm biệt'),
        (2, 'Computer', 'computer.png', '/kəmˈpjuː.tər/', 'Máy tính')
    ";
    
    //$conn->query($insert_flashcard_query);


    // Thêm dữ liệu mẫu vào bảng history
    $insert_history_query = "
        INSERT INTO history (user_id, duration)
        VALUES 
        (1, '00:30:00'),
        (2, '01:00:00')
    ";
    //$conn->query($insert_history_query);

    // Thêm dữ liệu mẫu vào bảng reminder
    $insert_reminder_query = "
        INSERT INTO reminder (user_id, reminder_date, status)
        VALUES 
        (1, '2024-11-30', 'Pending'),
        (2, '2024-12-01', 'Complete')
    ";
    //$conn->query($insert_reminder_query);
    
    $insert_default_messages_query = "INSERT INTO default_messages (message_type, message_text) VALUES
    ('daily', 'Hôm nay Apple có nhiều từ vựng mới thú vị lắm nè, bạn {username} vào học cùng tớ nhé =33 ♥♥♥.'),
    ('48_hours', 'Đằng ấy ơi, bạn có niềm vui gì mới mà quên luôn Apple rồi sao? Apple cảm thấy buồn, hãy vô học với Apple để Apple thấy vui hơn nhé ^^.')";
    //$conn->query($insert_default_messages_query); 
    ?>